## Player Level Analysis: Difference Between High-Leverage and Low-Leverage FOW% Charts
## Top 10 FOW% Increase and Decrease in High-Leverage by Player

## reading in necessary libraries and mirrored faceoff dataset
library(tidyverse)
library(classInt)
library(gt)
library(gtExtras)
library(ggplot2)

faceoffData = readRDS('faceoffData.rds')


## using Jenks Natural Breaks to find natural breaks in leverage score
## (essentially the 1D equivalent to k-means clustering)
set.seed(91)
leverageBreaks <- faceoffData |>
  distinct(eventId, .keep_all = TRUE) |>
  pull(leverage) |>
  classIntervals(n = 3, style = "jenks")


# use: leverageBreaks$brks to see the resulting breaks generated by the algorithm


## creating a column that indicates the leverage group (high, medium, low)
## that each faceoff belongs to according to the Jenks algorithm
faceoffData = faceoffData |>
  mutate(
    bins = cut(leverage,
      breaks = leverageBreaks$brks,
      include.lowest = TRUE,
      labels = c("Low", "Medium", "High")
    )
  )


## creating a dataframe with each player's raw FOW% for each leverage group
## (high, medium and low); includes all players with >= 50 high leverage faceoffs taken
fow_byLeverage <- faceoffData |>
  group_by(faceoffPlayerId, player) |>
  summarise(
    
    overallAttempts = n(),
    overallWins = sum(faceoffWon == 1),
    
    highleverageAttempts = sum(bins == 'High'),
    highleverageWins = sum(faceoffWon == 1 & bins == 'High'),
    
    lowleverageAttempts = sum(bins == 'Low'),
    lowleverageWins = sum(faceoffWon == 1 & bins == 'Low'),
    
    .groups = "drop"
  ) |>
  filter(highleverageAttempts >= 50) |>
  mutate(overallRawPct = overallWins / overallAttempts,
         rawHighLevPct = highleverageWins / highleverageAttempts,
         rawLowLevPct = lowleverageWins / lowleverageAttempts)



## general function for calculating prior needed for Empirical Bayes shrinkage
alphaBeta <- function(meanPct, varPct) {
  
  common <- meanPct * (1 - meanPct) / varPct - 1
  
  alpha <- meanPct * common
  beta <- (1 - meanPct) * common
  
  return(c(alpha = alpha, beta = beta))
}


## using Empirical Bayes shrinkage to calculate shrunk high leverage FOW%
highleverage_meanPct <- mean(fow_byLeverage$rawHighLevPct, na.rm = TRUE)
highleverage_varPct <- var(fow_byLeverage$rawHighLevPct, na.rm = TRUE)

prior <- alphaBeta(highleverage_meanPct, highleverage_varPct)

alpha = prior[1]
beta = prior[2]

fow_byLeverage = fow_byLeverage |>
  mutate(shrunkHighLevPct =
           ((rawHighLevPct * highleverageAttempts) + alpha) /
           (highleverageAttempts + alpha + beta))


## using Empirical Bayes shrinkage to calculate shrunk low leverage FOW%
lowleverage_meanPct <- mean(fow_byLeverage$rawLowLevPct, na.rm = TRUE)
lowleverage_varPct <- var(fow_byLeverage$rawLowLevPct, na.rm = TRUE)

prior <- alphaBeta(lowleverage_meanPct, lowleverage_varPct)

alpha = prior[1]
beta = prior[2]

fow_byLeverage = fow_byLeverage |>
  mutate(shrunkLowLevPct =
           ((rawLowLevPct * lowleverageAttempts) + alpha) /
           (lowleverageAttempts + alpha + beta))



## using Empirical Bayes shrinkage to calculate shrunk overall FOW%
overall_meanPct <- mean(fow_byLeverage$overallRawPct, na.rm = TRUE)
overall_varPct <- var(fow_byLeverage$overallRawPct, na.rm = TRUE)

prior <- alphaBeta(overall_meanPct, overall_varPct)

alpha = prior[1]
beta = prior[2]

fow_byLeverage = fow_byLeverage |>
  mutate(shrunkOverallPct =
           ((overallRawPct * overallAttempts) + alpha) /
           (overallAttempts + alpha + beta))

## creating a copy of the existing dataframe (with the player level FOW% by leverage)
workingFOW_byLeverage = fow_byLeverage


## calculating difference between high and low leverage success
fow_byLeverage = fow_byLeverage |>
  mutate(difference = shrunkHighLevPct - shrunkLowLevPct) |>
  arrange(desc(difference)) |>
  select(player, highleverageAttempts, difference) |>
  head(10)


## making the gt table for top 10 FOW% increase in high leverage 
tab1 = fow_byLeverage |>
  gt() |>
  tab_header(
    title = md("**Top 10 FOW% Increase in High Leverage**"),
    subtitle = "2021-22 to 2025-26 NHL Season - Minimum 50 High Leverage Faceoffs"
  ) %>%
  fmt_percent(columns = difference, 
              decimals = 2) |>
  cols_label(
    player = "Player",
    highleverageAttempts = 'High Lev. FO',
    difference = "FOW% Increase"
  ) %>%
  data_color(
    columns = difference,
    colors = scales::col_numeric(
      palette = c("white", "darkgreen"),
      domain = NULL
    )
  ) |>
  tab_options(
    table.font.names = "Arial"
  ) |>
  cols_width(
    player ~ px(175),
    difference ~ px(130) 
  ) |>
  cols_align(
    align = "center",
    columns = highleverageAttempts
  )



## making the gt table for top 10 FOW% decrease in high leverage 
tab2 = workingFOW_byLeverage |>
  mutate(difference = shrunkHighLevPct - shrunkLowLevPct) |>
  arrange((difference)) |>
  select(player, highleverageAttempts, difference) |>
  head(10) |>
  gt() |> 
  tab_header(
    title = md("**Top 10 FOW% Decrease in High Leverage**"),
    subtitle = "2021-22 to 2025-26 NHL Season - Minimum 50 High Leverage Faceoffs"
  ) |>
  fmt_percent(columns = difference, 
              decimals = 2) |>
  cols_label(
    player = "Player",
    highleverageAttempts = 'High Lev. FO',
    difference = "FOW% Decrease"
  ) %>%
  data_color(
    columns = difference,
    colors = scales::col_numeric(
      palette = c("red", "white"),
      domain = NULL
    )
  ) |>
  tab_options(
    table.font.names = "Arial"
  ) |>
  cols_width(
    player ~ px(175),
    difference ~ px(140) 
  ) |>
  cols_align(
    align = "center",
    columns = highleverageAttempts
  )


## conjoining the two gt tables together
gt_two_column_layout(list(tab1, tab2))



## table indicating the leverage break cut-offs
breaks = as.data.frame(leverageBreaks$brks) |>
  rename(startPoint = 'leverageBreaks$brks') |>
  mutate(endPoint = lead(startPoint)) |>
  mutate(startPoint = as.character(startPoint),
         endPoint = as.character(endPoint)) |>
  mutate(interval = paste(startPoint, endPoint, sep = " - ")) |>
  mutate(leverageGroup = c('Low','Medium','High',NA)) |>
  head(3) |>
  select(leverageGroup, interval)

breaks |>
  gt() |>
  tab_header(
    title = md("**Leverage Score Groupings**"),
    subtitle = 'Derived using Jenks Natural Breaks algorithm with three breaks'
  ) |>
  cols_label(
    leverageGroup = "Leverage Group",
    interval = 'Score Interval'
  ) |>
  tab_options(
    table.font.names = "Arial"
  ) |>
  cols_align(
    align = "center",
    columns = c(interval, leverageGroup)
  ) |>
  tab_style(
    style = list(
      cell_fill(color = "#79BAEC"),
      cell_text(color = 'white')
    ),
    locations = cells_body(rows = 1)
  ) |>
  tab_style(
    style = list(
      cell_fill(color = "#4682B4"),
      cell_text(color = 'white')
    ),
    locations = cells_body(rows = 2)
  ) |>
  tab_style(
    style = list(
      cell_fill(color = "#123456"),
      cell_text(color = 'white')
    ),
    locations = cells_body(rows = 3)
  )


